# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpup < Formula
  desc "Manage MCP server configs across AI clients from one place"
  homepage "https://github.com/mohammedsamin/mcpup"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mohammedsamin/mcpup/releases/download/v0.2.0/mcpup_0.2.0_darwin_amd64.tar.gz"
      sha256 "7c4234fc3d23eccfbcca487d0f8d52c5beaea4fc87fe57b7bcd991128fb82ab8"

      define_method(:install) do
        bin.install "mcpup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mohammedsamin/mcpup/releases/download/v0.2.0/mcpup_0.2.0_darwin_arm64.tar.gz"
      sha256 "0cff24667841cc386cc11d13beb86de9cd261edc631f424c01b55c65eecab977"

      define_method(:install) do
        bin.install "mcpup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohammedsamin/mcpup/releases/download/v0.2.0/mcpup_0.2.0_linux_amd64.tar.gz"
      sha256 "38cc1806f04b8d4dd8f4fc48bd90395ba44643b7b1dbffded60434bf54c9108e"
      define_method(:install) do
        bin.install "mcpup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mohammedsamin/mcpup/releases/download/v0.2.0/mcpup_0.2.0_linux_arm64.tar.gz"
      sha256 "93aa23b45512b26f0c40244ebb160469c2be34ddf570760313ef8d6dca2df806"
      define_method(:install) do
        bin.install "mcpup"
      end
    end
  end

  test do
    system bin/"mcpup", "help"
  end
end
